---
instance_name: A - Z # Read Spice doc
symbol: string # Path to svg (Optional), defaults to a box

dimensions:
  width: number
  height: number

top-ports: # Array of ports
  - name: string # Port name/identifier (Optional)
    x: number # Port X coordinate
    y: number # Port Y coordinate

right-ports: []

bottom-ports: []

left-ports: []

fields: # Dict of dicts
  - type: string # number | string | select
    validation: string # regexp for value validation (Optional)
    options: [] # Array of strings if type == select
    name: string # Name of the field
